server:
  port: 8080
  servlet:
    context-path: /
    encoding: UTF-8
    enabled: true
    force: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

jwt:
  issuer: jeonguk9802@gmail.com
  secret_key: jplan